# Generated by Django 4.0.4 on 2022-05-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausername', models.TextField(default='')),
                ('apassword', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Bevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocation', models.TextField(default='')),
                ('bevent', models.TextField(default='')),
                ('bdate', models.TextField(default='')),
                ('bbstime', models.TextField(default='')),
                ('bbetime', models.TextField(default='')),
                ('bhours', models.TextField(default='')),
                ('brates', models.TextField(default='')),
                ('bpeople', models.TextField(default='')),
                ('bstat', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Rinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rlname', models.TextField(default='')),
                ('rfname', models.TextField(default='')),
                ('rmname', models.TextField(default='')),
                ('raddress', models.TextField(default='')),
                ('rage', models.TextField(default='')),
                ('rcnumber', models.TextField(default='')),
                ('runame', models.TextField(default='')),
                ('rpass', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Zstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='')),
                ('sremarks', models.TextField(default='')),
                ('bevent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='KDBES.bevent')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llocation', models.TextField(default='')),
                ('laddress', models.TextField(default='')),
                ('bevent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='KDBES.bevent')),
            ],
        ),
        migrations.AddField(
            model_name='bevent',
            name='rinfo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='KDBES.rinfo'),
        ),
    ]
