# Generated by Django 4.0.4 on 2022-05-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDBES', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bevent',
            old_name='bevent',
            new_name='bbevents',
        ),
    ]
