# Generated by Django 4.0.4 on 2022-05-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDBES', '0002_rename_bevent_bevent_bbevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bevent',
            old_name='bbevents',
            new_name='bcategory',
        ),
    ]
