# Generated by Django 4.0.4 on 2022-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDBES', '0004_rename_ainfo_areg_rename_zstatus_zremarks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Zlocation',
        ),
    ]
