# Generated by Django 4.0.4 on 2022-06-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDBES', '0005_rename_location_zlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bevent',
            old_name='bcategory',
            new_name='bmainevent',
        ),
    ]
